const questions = [
  {
    "Categoria": "Personagem",
    "Resposta": "Harry Potter",
    "Dica1": "Sou o protagonista de uma série de livros de fantasia.",
    "Dica2": "Descobri minha verdadeira natureza aos 11 anos.",
    "Dica3": "Tenho uma cicatriz em forma de raio na testa.",
    "Dica4": "Estudei em uma escola de magia chamada Hogwarts.",
    "Dica5": "Meus melhores amigos são Rony e Hermione.",
    "Dica6": "Pertenço à casa Grifinória.",
    "Dica7": "Possuo uma coruja de estimação chamada Edwiges.",
    "Dica8": "Utilizo uma varinha e uma vassoura voadora.",
    "Dica9": "\"Sou conhecido como \"\"O Menino que Sobreviveu\"\".\"",
    "Dica10": "Sou o bruxo que derrotou Lord Voldemort."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Paris",
    "Dica1": "Sou uma capital europeia.",
    "Dica2": "Sou conhecida pelo meu charme e romance.",
    "Dica3": "Sou cortada pelo Rio Sena.",
    "Dica4": "Tenho uma arquitetura histórica e icônica.",
    "Dica5": "Sou um dos centros mundiais da moda.",
    "Dica6": "Sou a sede do museu mais visitado do mundo (Louvre).",
    "Dica7": "Meu ponto turístico mais famoso foi construído para uma feira mundial.",
    "Dica8": "\"Sou chamada de \"\"Cidade Luz\"\".\"",
    "Dica9": "Minha culinária é famosa por croissants e queijos.",
    "Dica10": "Abrigo a famosa Torre Eiffel."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Albert Einstein",
    "Dica1": "Nasci no século XIX.",
    "Dica2": "Sou conhecido por minha inteligência.",
    "Dica3": "Fui físico teórico.",
    "Dica4": "Nasci na Alemanha.",
    "Dica5": "Sou famoso por uma teoria sobre o tempo e o espaço.",
    "Dica6": "Ganhei o Prêmio Nobel de Física.",
    "Dica7": "Minha imagem com cabelo bagunçado é icônica.",
    "Dica8": "Minha equação mais conhecida é E=mc²",
    "Dica9": "Fugi do nazismo e fui morar nos Estados Unidos.",
    "Dica10": "Meu nome virou sinônimo de gênio."
  },
  {
    "Categoria": "Animal",
    "Resposta": "Elefante",
    "Dica1": "Sou um mamífero terrestre.",
    "Dica2": "Vivo em grupos sociais complexos.",
    "Dica3": "Tenho uma excelente memória.",
    "Dica4": "Sou herbívoro e consumo grandes quantidades de vegetação.",
    "Dica5": "Minha gestação é uma das mais longas do reino animal (22 meses).",
    "Dica6": "Tenho presas de marfim que infelizmente atraem caçadores.",
    "Dica7": "Sou o maior animal terrestre vivo na atualidade.",
    "Dica8": "Minhas orelhas ajudam a regular minha temperatura corporal.",
    "Dica9": "Sou encontrado naturalmente na África e na Ásia.",
    "Dica10": "Minha característica física mais marcante é a longa tromba."
  },
  {
    "Categoria": "Ano",
    "Resposta": "1945",
    "Dica1": "Pertenço à primeira metade do século XX.",
    "Dica2": "Foi um ano que mudou a geografia do mundo.",
    "Dica3": "Marcou a criação da ONU.",
    "Dica4": "Pessoas saíram às ruas para comemorar o fim de um conflito.",
    "Dica5": "Infelizmente, vi o primeiro uso de bombas atômicas.",
    "Dica6": "Líderes como Hitler e Mussolini morreram neste ano.",
    "Dica7": "Marcou o início da transição para a Guerra Fria.",
    "Dica8": "No Brasil, terminou o Estado Novo de Getúlio Vargas.",
    "Dica9": "Foi o ano em que a Alemanha se rendeu.",
    "Dica10": "Sou o ano em que terminou a Segunda Guerra Mundial."
  },
  {
    "Categoria": "Obra",
    "Resposta": "Mona Lisa",
    "Dica1": "Sou uma obra de arte mundialmente famosa.",
    "Dica2": "Fui pintada no início do século XVI.",
    "Dica3": "Sou uma pintura a óleo sobre madeira de álamo.",
    "Dica4": "Meu autor é o maior polímata do Renascimento.",
    "Dica5": "\"Sou conhecida pela técnica de \"\"sfumato\"\".\"",
    "Dica6": "Meu sorriso é considerado um dos maiores mistérios da arte.",
    "Dica7": "Fui roubada do Museu do Louvre em 1911.",
    "Dica8": "\"Também sou conhecida pelo nome \"\"La Gioconda\"\".\"",
    "Dica9": "Fui criada por Leonardo da Vinci.",
    "Dica10": "Sou o retrato de uma mulher que parece observar o espectador de qualquer ângulo."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Steve Jobs",
    "Dica1": "Nasci no século XX nos EUA.",
    "Dica2": "Fui um visionário da tecnologia.",
    "Dica3": "Comecei uma empresa em uma garagem com um amigo.",
    "Dica4": "Fui demitido da minha própria empresa e depois voltei.",
    "Dica5": "Revolucionei a indústria da música com o iPod.",
    "Dica6": "Era conhecido por vestir sempre calça jeans e blusa preta.",
    "Dica7": "Ajudei a fundar a Pixar.",
    "Dica8": "Minha empresa tem o nome de uma fruta.",
    "Dica9": "Sou o rosto por trás do lançamento do primeiro iPhone.",
    "Dica10": "Sou o cofundador da Apple."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Amazônia",
    "Dica1": "Sou uma vasta região geográfica.",
    "Dica2": "Abrigo a maior biodiversidade do planeta.",
    "Dica3": "Sou essencial para a regulação do clima global.",
    "Dica4": "Estendo-me por nove países da América do Sul.",
    "Dica5": "Sou cortada pelo maior rio em volume de água do mundo.",
    "Dica6": "Minha vegetação é densa e predominantemente tropical.",
    "Dica7": "Sofro constantemente com ameaças de desmatamento.",
    "Dica8": "Grande parte do meu território está no Brasil.",
    "Dica9": "\"Sou chamada de \"\"Pulmão do Mundo\"\".\"",
    "Dica10": "Sou a maior floresta tropical do mundo."
  },
  {
    "Categoria": "Comida",
    "Resposta": "Chocolate",
    "Dica1": "Sou um alimento derivado de uma fruta tropical.",
    "Dica2": "Minha base é o cacau.",
    "Dica3": "Fui consumido como bebida amarga pelos astecas e maias.",
    "Dica4": "Tornei-me sólido e doce após processos industriais.",
    "Dica5": "Posso ser encontrado nas versões ao leite, amargo ou branco.",
    "Dica6": "Sou o ingrediente principal dos ovos de Páscoa.",
    "Dica7": "Libero substâncias que trazem bem-estar.",
    "Dica8": "Sou frequentemente dado em caixas de bombons.",
    "Dica9": "Derreto facilmente em temperaturas próximas à do corpo.",
    "Dica10": "Sou o doce mais amado e consumido do mundo."
  },
  {
    "Categoria": "Personagem",
    "Resposta": "Batman",
    "Dica1": "Sou um super-herói das histórias em quadrinhos.",
    "Dica2": "Não possuo superpoderes sobre-humanos.",
    "Dica3": "Minha identidade secreta é um bilionário órfão.",
    "Dica4": "Vivo em uma cidade fictícia chamada Gotham City.",
    "Dica5": "Utilizo tecnologia avançada e artes marciais.",
    "Dica6": "Tenho um mordomo fiel chamado Alfred.",
    "Dica7": "Meu símbolo é inspirado em um animal noturno.",
    "Dica8": "Meus pais foram mortos em um beco.",
    "Dica9": "Meu maior inimigo é o Coringa.",
    "Dica10": "\"Sou conhecido como o \"\"Cavaleiro das Trevas\"\".\""
  },
  {
    "Categoria": "Ano",
    "Resposta": "1500",
    "Dica1": "Sou um ano de transição de século.",
    "Dica2": "Pertenço à Idade Moderna.",
    "Dica3": "Começo com o numeral 1.",
    "Dica4": "Foi um período de Grandes Navegações.",
    "Dica5": "Na Europa, o Renascimento estava em alta.",
    "Dica6": "Sou um ano bissexto.",
    "Dica7": "Uma frota portuguesa atravessou o Atlântico neste ano.",
    "Dica8": "Pedro Álvares Cabral liderava essa expedição.",
    "Dica9": "Chegamos a terras que seriam chamadas de Vera Cruz.",
    "Dica10": "\"Sou o ano do \"\"descobrimento\"\" oficial do Brasil.\""
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Pelé",
    "Dica1": "Nasci no século XX.",
    "Dica2": "Sou brasileiro.",
    "Dica3": "Fui um atleta profissional.",
    "Dica4": "Sou conhecido mundialmente por um esporte de massa.",
    "Dica5": "Estreei em uma Copa com apenas 17 anos.",
    "Dica6": "Marquei mais de mil gols em minha carreira.",
    "Dica7": "Joguei a maior parte da vida no Santos.",
    "Dica8": "Sou o único jogador a vencer três Copas do Mundo.",
    "Dica9": "Usei a mítica camisa número 10.",
    "Dica10": "\"Sou amplamente chamado de o \"\"Rei do Futebol\"\".\""
  },
  {
    "Categoria": "Fenômeno",
    "Resposta": "Arco-íris",
    "Dica1": "Sou um fenômeno óptico e meteorológico.",
    "Dica2": "Ocorro quando a luz solar interage com gotas de água.",
    "Dica3": "Apareço geralmente logo após ou durante uma chuva.",
    "Dica4": "Tenho o formato de um arco multicolorido no céu.",
    "Dica5": "Sou composto pela decomposição da luz branca.",
    "Dica6": "Possuo sete cores principais visíveis.",
    "Dica7": "Na mitologia, sou visto como uma ponte.",
    "Dica8": "No folclore irlandês, haveria um pote de ouro no fim.",
    "Dica9": "Vermelho, laranja, amarelo, verde, azul, anil e violeta são minhas cores.",
    "Dica10": "Sou a manifestação visual do espectro solar após a chuva."
  },
  {
    "Categoria": "Obra",
    "Resposta": "Romeu e Julieta",
    "Dica1": "Sou uma obra clássica da literatura.",
    "Dica2": "Fui escrita no final do século XVI.",
    "Dica3": "Sou uma tragédia sobre dois jovens apaixonados.",
    "Dica4": "Minha história se passa na cidade de Verona, Itália.",
    "Dica5": "Meu autor é William Shakespeare.",
    "Dica6": "As famílias dos protagonistas são rivais.",
    "Dica7": "Sou o símbolo máximo do amor proibido.",
    "Dica8": "Fui adaptada inúmeras vezes para o cinema.",
    "Dica9": "Minha cena mais famosa acontece em um balcão.",
    "Dica10": "Sou a peça de teatro mais famosa de Shakespeare."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Roma",
    "Dica1": "Sou uma das cidades mais antigas da Europa.",
    "Dica2": "\"Sou conhecida como a \"\"Cidade Eterna\"\".\"",
    "Dica3": "Fui o centro de um dos maiores impérios da história.",
    "Dica4": "Tenho um país inteiro dentro do meu território.",
    "Dica5": "Sou famosa por minhas sete colinas.",
    "Dica6": "Minha arquitetura inclui aquedutos.",
    "Dica7": "O rio que me atravessa é o Tibre.",
    "Dica8": "Abrigo as ruínas do Fórum e do Panteão.",
    "Dica9": "Sou a capital da Itália.",
    "Dica10": "O Coliseu é meu monumento mais icônico."
  },
  {
    "Categoria": "Animal",
    "Resposta": "Girafa",
    "Dica1": "Sou um mamífero herbívoro.",
    "Dica2": "Vivo nas savanas africanas.",
    "Dica3": "Possuo uma língua azulada e comprida.",
    "Dica4": "Consigo comer folhas nos topos das árvores.",
    "Dica5": "Minha pele é coberta por manchas irregulares.",
    "Dica6": "Tenho dois pequenos chifres cobertos de pele.",
    "Dica7": "Consigo passar dias sem beber água.",
    "Dica8": "Meu coração é muito forte para bombear sangue até a cabeça.",
    "Dica9": "Sou o animal mais alto do mundo.",
    "Dica10": "Meu pescoço é extremamente longo."
  },
  {
    "Categoria": "Ano",
    "Resposta": "1989",
    "Dica1": "Pertenço à segunda metade do século XX.",
    "Dica2": "Foi um ano de grandes mudanças geopolíticas.",
    "Dica3": "Na computação, a WWW começou a ser idealizada.",
    "Dica4": "No Brasil, ocorreram as primeiras eleições diretas pós-ditadura.",
    "Dica5": "O mundo assistiu ao massacre na Praça da Paz Celestial.",
    "Dica6": "Sou o ano em que os Simpsons estreou.",
    "Dica7": "\"A música \"\"Lambada\"\" era um sucesso mundial.\"",
    "Dica8": "Ocorreu a queda de um muro que dividia uma cidade alemã.",
    "Dica9": "Marcou o início do fim da Guerra Fria.",
    "Dica10": "Sou o ano da queda do Muro de Berlim."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Cleópatra",
    "Dica1": "Vivi antes da era cristã.",
    "Dica2": "Fui uma das mulheres mais poderosas da Antiguidade.",
    "Dica3": "Governei uma nação africana.",
    "Dica4": "Tive relacionamentos com líderes romanos.",
    "Dica5": "Sou a última governante do Reino Ptolemaico.",
    "Dica6": "Sou retratada com maquiagem marcante.",
    "Dica7": "Minha linhagem era de origem grega.",
    "Dica8": "Diz a lenda que me suicidei com uma cobra.",
    "Dica9": "Vivi na cidade de Alexandria.",
    "Dica10": "Fui a Rainha do Egito."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Muralha da China",
    "Dica1": "Sou uma das maiores estruturas já construídas.",
    "Dica2": "Sou feita de pedra, tijolo e terra.",
    "Dica3": "Fui construída ao longo de vários séculos.",
    "Dica4": "Minha função original era proteção contra invasões.",
    "Dica5": "Atravesso desertos e montanhas.",
    "Dica6": "Sou uma das Novas Sete Maravilhas do Mundo.",
    "Dica7": "Tenho milhares de quilômetros de extensão.",
    "Dica8": "Possuo diversas torres de vigia.",
    "Dica9": "Sou o principal símbolo turístico do meu país.",
    "Dica10": "Sou a fortificação visível do alto no leste asiático."
  },
  {
    "Categoria": "Evento",
    "Resposta": "Natal",
    "Dica1": "Sou uma celebração anual de grande importância.",
    "Dica2": "Tenho origens cristãs.",
    "Dica3": "Ocorro no mês de dezembro.",
    "Dica4": "Sou uma época de reuniões familiares.",
    "Dica5": "Minha decoração inclui árvores enfeitadas.",
    "Dica6": "Ceias especiais são preparadas na minha véspera.",
    "Dica7": "Crianças costumam escrever cartas pedindo brinquedos.",
    "Dica8": "Minha figura comercial veste vermelho e branco.",
    "Dica9": "Sou celebrado no dia 25 de dezembro.",
    "Dica10": "Minha figura central lendária é o Papai Noel."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Leonardo da Vinci",
    "Dica1": "Vivi durante o Renascimento.",
    "Dica2": "Nasci na Itália.",
    "Dica3": "Fui pintor, escultor e inventor.",
    "Dica4": "Estudei anatomia humana escondido.",
    "Dica5": "Projetei máquinas voadoras séculos antes do avião.",
    "Dica6": "\"Sou o autor do \"\"Homem Vitruviano\"\".\"",
    "Dica7": "Pintei uma famosa ceia em Milão.",
    "Dica8": "Sou mestre na técnica do sfumato.",
    "Dica9": "Minha obra mais famosa está no Louvre.",
    "Dica10": "\"Sou o autor da \"\"Mona Lisa\"\".\""
  },
  {
    "Categoria": "Animal",
    "Resposta": "Tubarão",
    "Dica1": "Sou um peixe cartilaginoso.",
    "Dica2": "Habito oceanos e mares por todo o mundo.",
    "Dica3": "Não possuo ossos, meu esqueleto é de cartilagem.",
    "Dica4": "Meus dentes são substituídos continuamente.",
    "Dica5": "Possuo fendas branquiais nas laterais.",
    "Dica6": "Tenho um olfato apurado para detectar sangue.",
    "Dica7": "Algumas espécies precisam nadar constantemente para respirar.",
    "Dica8": "Fui protagonista de um filme de Spielberg.",
    "Dica9": "Minha barbatana dorsal na água causa medo.",
    "Dica10": "\"O \"\"Branco\"\" é minha espécie mais famosa.\""
  },
  {
    "Categoria": "Personagem",
    "Resposta": "Sherlock Holmes",
    "Dica1": "Sou um personagem da literatura de ficção.",
    "Dica2": "Vivo em Londres na era vitoriana.",
    "Dica3": "Apareci pela primeira vez em um livro de 1887.",
    "Dica4": "Sou conhecido pela lógica dedutiva.",
    "Dica5": "Meu criador foi Sir Arthur Conan Doyle.",
    "Dica6": "Tenho um fiel companheiro chamado Dr. Watson.",
    "Dica7": "Meu endereço é 221B Baker Street.",
    "Dica8": "\"Uso um chapéu \"\"deerstalker\"\" e um cachimbo.\"",
    "Dica9": "Meu maior inimigo é o Professor Moriarty.",
    "Dica10": "Sou o detetive mais famoso de todos os tempos."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Nova York",
    "Dica1": "Localizo-me na costa leste da América do Norte.",
    "Dica2": "Sou a cidade mais populosa do meu país.",
    "Dica3": "Sou um centro global de finanças.",
    "Dica4": "\"Sou apelidada de \"\"Big Apple\"\".\"",
    "Dica5": "Tenho cinco divisões principais.",
    "Dica6": "Abrigo a sede da ONU.",
    "Dica7": "Meus musicais são mundialmente famosos.",
    "Dica8": "Tenho um parque gigantesco no centro.",
    "Dica9": "Meus táxis amarelos são um símbolo.",
    "Dica10": "A Estátua da Liberdade fica em uma de minhas ilhas."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Santos Dumont",
    "Dica1": "Nasci em Minas Gerais no século XIX.",
    "Dica2": "Fui um inventor e aeronauta.",
    "Dica3": "Passei grande parte da vida na França.",
    "Dica4": "Projetei diversos balões dirigíveis.",
    "Dica5": "Sou creditado por popularizar o relógio de pulso.",
    "Dica6": "Ganhei o Prêmio Deutsch ao contornar a Torre Eiffel.",
    "Dica7": "\"Fui entusiasta da aviação \"\"mais pesada que o ar\"\".\"",
    "Dica8": "Minha casa em Petrópolis é um museu.",
    "Dica9": "Realizei o primeiro voo homologado em 1906.",
    "Dica10": "Sou o inventor do avião 14-Bis."
  },
  {
    "Categoria": "Coisa",
    "Resposta": "Computador",
    "Dica1": "Sou uma ferramenta de processamento de dados.",
    "Dica2": "Comecei com máquinas de calcular mecânicas.",
    "Dica3": "Evoluí de válvulas para microchips.",
    "Dica4": "Possuo hardware e software.",
    "Dica5": "Alan Turing é considerado um dos meus pais.",
    "Dica6": "Antigamente, eu ocupava salas inteiras.",
    "Dica7": "Hoje posso ser carregado em uma mochila.",
    "Dica8": "Tenho memória RAM e armazenamento.",
    "Dica9": "Utilizo o sistema binário (0 e 1).",
    "Dica10": "Sou o dispositivo onde você usa internet."
  },
  {
    "Categoria": "Fenômeno",
    "Resposta": "Aurora Boreal",
    "Dica1": "Sou um espetáculo de luzes naturais no céu.",
    "Dica2": "Ocorro devido ao impacto de partículas solares.",
    "Dica3": "Sou visível apenas em altas latitudes do Norte.",
    "Dica4": "\"Minha versão no Sul chama-se \"\"Austral\"\".\"",
    "Dica5": "Exibo cores como verde e violeta.",
    "Dica6": "Pareço cortinas dançantes no céu noturno.",
    "Dica7": "Países como Noruega e Islândia são ótimos para me ver.",
    "Dica8": "Sou alvo de fotógrafos de natureza.",
    "Dica9": "A melhor época é durante o inverno polar.",
    "Dica10": "\"Sou as famosas \"\"Luzes do Norte\"\".\""
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Machado de Assis",
    "Dica1": "Nasci no Rio de Janeiro no século XIX.",
    "Dica2": "Tive origens humildes e fui autodidata.",
    "Dica3": "Fui jornalista, cronista e poeta.",
    "Dica4": "Sou o maior nome da literatura brasileira.",
    "Dica5": "Fui um dos fundadores da ABL.",
    "Dica6": "Minha obra é dividida em Romântica e Realista.",
    "Dica7": "Criei personagens como Capitu e Bentinho.",
    "Dica8": "\"Escrevi \"\"Memórias Póstumas de Brás Cubas\"\".\"",
    "Dica9": "\"Sou o \"\"Bruxo do Cosme Velho\"\".\"",
    "Dica10": "\"Sou o autor do clássico \"\"Dom Casmurro\"\".\""
  },
  {
    "Categoria": "Ano",
    "Resposta": "1969",
    "Dica1": "Pertenço à década de 60.",
    "Dica2": "Foi um ano de grandes avanços tecnológicos.",
    "Dica3": "Ocorreu o festival de Woodstock.",
    "Dica4": "A internet deu seus primeiros passos.",
    "Dica5": "Os Beatles fizeram sua última apresentação no telhado.",
    "Dica6": "No Brasil, vivia-se o período do AI-5.",
    "Dica7": "A missão Apollo 11 foi lançada neste ano.",
    "Dica8": "Neil Armstrong foi o primeiro homem a pisar na Lua.",
    "Dica9": "\"\"\"Um pequeno passo para um homem...\"\".\"",
    "Dica10": "Sou o ano em que o homem chegou à Lua."
  },
  {
    "Categoria": "Evento",
    "Resposta": "Olimpíadas",
    "Dica1": "Sou uma celebração esportiva global.",
    "Dica2": "Ocorro regularmente a cada quatro anos.",
    "Dica3": "Minhas origens remontam à Grécia Antiga.",
    "Dica4": "Minha versão moderna foi revivida por Coubertin.",
    "Dica5": "Reuno atletas de quase todos os países.",
    "Dica6": "Possuo versões de Verão e de Inverno.",
    "Dica7": "Meu símbolo consiste em cinco anéis coloridos.",
    "Dica8": "O acendimento de uma pira marca o início.",
    "Dica9": "Atletas competem por medalhas.",
    "Dica10": "Sou o maior espetáculo esportivo da humanidade."
  },
  {
    "Categoria": "Personagem",
    "Resposta": "Mickey Mouse",
    "Dica1": "Sou uma figura icônica da cultura pop mundial.",
    "Dica2": "\"Minha primeira aparição foi em \"\"Steamboat Willie\"\".\"",
    "Dica3": "Fui criado por Walt Disney em 1928.",
    "Dica4": "Tenho uma voz aguda e sapatos amarelos.",
    "Dica5": "Minha namorada chama-se Minnie.",
    "Dica6": "Tenho um cachorro chamado Pluto.",
    "Dica7": "Sou o principal símbolo de um império.",
    "Dica8": "Uso luvas brancas e bermuda vermelha.",
    "Dica9": "Tenho orelhas redondas pretas reconhecíveis.",
    "Dica10": "Sou o rato mais famoso do mundo."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Japão",
    "Dica1": "Sou uma nação insular.",
    "Dica2": "Estou localizado no leste da Ásia.",
    "Dica3": "\"Sou conhecido como \"\"Terra do Sol Nascente\"\".\"",
    "Dica4": "Minha geografia é marcada por vulcões.",
    "Dica5": "Sou líder mundial em eletrônicos.",
    "Dica6": "Minha culinária usa muito peixe cru.",
    "Dica7": "Sou a terra dos samurais e ninjas.",
    "Dica8": "Minhas cerejeiras são famosas.",
    "Dica9": "Minha capital é a cidade mais populosa do mundo.",
    "Dica10": "Sou o arquipélago onde fica o Monte Fuji."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Marie Curie",
    "Dica1": "Nasci no século XIX.",
    "Dica2": "Fui uma cientista pioneira.",
    "Dica3": "Nasci na Polônia, fiz carreira na França.",
    "Dica4": "Primeira mulher a ganhar um Nobel.",
    "Dica5": "Ganhei dois Prêmios Nobel em áreas diferentes.",
    "Dica6": "Estudei a radioatividade.",
    "Dica7": "Descobri Polônio e Rádio.",
    "Dica8": "Desenvolvi unidades de raio-X na 1ª Guerra.",
    "Dica9": "Meus cadernos são radioativos até hoje.",
    "Dica10": "Meu sobrenome é sinônimo de ciência nuclear."
  },
  {
    "Categoria": "Animal",
    "Resposta": "Leão",
    "Dica1": "Sou um mamífero carnívoro.",
    "Dica2": "Vivo predominantemente em savanas.",
    "Dica3": "Sou um animal social (alcateias).",
    "Dica4": "Tenho garras retráteis e caninos grandes.",
    "Dica5": "Sou predador de topo de cadeia.",
    "Dica6": "Meu rugido pode ser ouvido a quilômetros.",
    "Dica7": "As fêmeas são as principais caçadoras.",
    "Dica8": "Sou um dos símbolos do zodíaco.",
    "Dica9": "Os machos possuem uma juba imponente.",
    "Dica10": "\"Sou conhecido como o \"\"Rei da Selva\"\".\""
  },
  {
    "Categoria": "Comida",
    "Resposta": "Pizza",
    "Dica1": "Sou um prato extremamente popular.",
    "Dica2": "Minha base é feita de massa de trigo.",
    "Dica3": "Sou geralmente assada em fornos de alta temperatura.",
    "Dica4": "Minha origem moderna é Nápoles, Itália.",
    "Dica5": "Sou circular, servida em fatias triangulares.",
    "Dica6": "Tenho infinitas variações de coberturas.",
    "Dica7": "\"O sabor \"\"Marguerita\"\" usa as cores da Itália.\"",
    "Dica8": "Sou um dos itens mais pedidos no delivery.",
    "Dica9": "Queijo e molho de tomate são obrigatórios.",
    "Dica10": "Minha embalagem tradicional é quadrada."
  },
  {
    "Categoria": "Ano",
    "Resposta": "2000",
    "Dica1": "Marquei o início de um novo milênio.",
    "Dica2": "\"Havia um medo chamado \"\"Bug do Milênio\"\".\"",
    "Dica3": "Ocorreram os Jogos de Sydney.",
    "Dica4": "A PlayStation 2 foi lançada.",
    "Dica5": "Putin assumiu a presidência da Rússia.",
    "Dica6": "Sou um ano bissexto.",
    "Dica7": "\"O filme \"\"Gladiador\"\" foi sucesso.\"",
    "Dica8": "No Brasil, comemorou-se os 500 anos.",
    "Dica9": "Começo com o numeral 2.",
    "Dica10": "Sou o último ano do século XX."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Austrália",
    "Dica1": "Sou um país e um continente.",
    "Dica2": "Localizo-me no Hemisfério Sul.",
    "Dica3": "Fui colonizada por britânicos.",
    "Dica4": "Meu interior é árido (Outback).",
    "Dica5": "Abrigo a Grande Barreira de Corais.",
    "Dica6": "Minha maior cidade é Sydney.",
    "Dica7": "Sou famosa por animais perigosos.",
    "Dica8": "Tenho uma famosa Casa de Ópera.",
    "Dica9": "Sou a terra dos aborígenes.",
    "Dica10": "Sou o habitat de cangurus e coalas."
  },
  {
    "Categoria": "Pessoa",
    "Resposta": "Isaac Newton",
    "Dica1": "Nasci no século XVII.",
    "Dica2": "Fui matemático e físico.",
    "Dica3": "Nasci na Inglaterra.",
    "Dica4": "Formulei as leis do movimento.",
    "Dica5": "Desenvolvi o cálculo infinitesimal.",
    "Dica6": "Fiz descobertas sobre a óptica.",
    "Dica7": "Estudei a gravitação universal.",
    "Dica8": "Dizem que uma maçã caiu na minha cabeça.",
    "Dica9": "\"Escrevi a obra \"\"Principia\"\".\"",
    "Dica10": "Meu sobrenome é unidade de medida de força."
  },
  {
    "Categoria": "Obra",
    "Resposta": "O Grito",
    "Dica1": "Sou uma pintura mundialmente reconhecida.",
    "Dica2": "Fui criada em 1893.",
    "Dica3": "Meu autor é Edvard Munch.",
    "Dica4": "Sou um ícone do Expressionismo.",
    "Dica5": "Represento a angústia moderna.",
    "Dica6": "Minhas cores são vibrantes e formas distorcidas.",
    "Dica7": "Ao fundo, há duas figuras em uma ponte.",
    "Dica8": "Fui alvo de roubos famosos em Oslo.",
    "Dica9": "Imagem usada em paródias e cultura pop.",
    "Dica10": "Represento uma figura com as mãos no rosto."
  },
  {
    "Categoria": "Coisa",
    "Resposta": "Automóvel",
    "Dica1": "Sou um meio de transporte terrestre.",
    "Dica2": "Produção em massa começou com o Ford T.",
    "Dica3": "Geralmente utilizo quatro rodas.",
    "Dica4": "Movido a combustão ou eletricidade.",
    "Dica5": "Exijo licenciamento e seguro.",
    "Dica6": "Possuo cintos e airbags.",
    "Dica7": "Motor medido em cavalos (cv).",
    "Dica8": "Tenho volante e pedais.",
    "Dica9": "Preciso de combustível para rodar.",
    "Dica10": "\"Sou popularmente conhecido como \"\"carro\"\".\""
  },
  {
    "Categoria": "Evento",
    "Resposta": "Carnaval",
    "Dica1": "Sou uma festa de origem religiosa.",
    "Dica2": "Celebrado em muitos países.",
    "Dica3": "Feriado nacional em várias cidades brasileiras.",
    "Dica4": "Marcado por desfiles e fantasias.",
    "Dica5": "No Rio, aconteço no Sambódromo.",
    "Dica6": "Em Veneza, as máscaras são tradição.",
    "Dica7": "Na Bahia, sou acompanhado por trios.",
    "Dica8": "Escolas de samba competem por títulos.",
    "Dica9": "\"Conhecido como \"\"Festa da Carne\"\".\"",
    "Dica10": "Sou a maior festa popular do Brasil."
  },
  {
    "Categoria": "Animal",
    "Resposta": "Tartaruga",
    "Dica1": "Sou um réptil.",
    "Dica2": "Existo há mais de 200 milhões de anos.",
    "Dica3": "Vivo em terra ou na água.",
    "Dica4": "Não possuo dentes, mas um bico rígido.",
    "Dica5": "Conhecida pela lentidão em terra.",
    "Dica6": "Minhas patas podem ser nadadeiras.",
    "Dica7": "Ponho ovos na areia.",
    "Dica8": "Posso passar dos 100 anos.",
    "Dica9": "Minha proteção é a carapaça dura.",
    "Dica10": "\"Carrego minha \"\"casa\"\" nas costas.\""
  },
  {
    "Categoria": "Coisa",
    "Resposta": "Livro",
    "Dica1": "Posso ser físico ou digital.",
    "Dica2": "Suporte para conhecimento e imaginação.",
    "Dica3": "Existia em rolos de pergaminho.",
    "Dica4": "Prensa de Gutenberg revolucionou minha produção.",
    "Dica5": "Possuo uma capa protetora.",
    "Dica6": "Composto por páginas numeradas.",
    "Dica7": "Posso ser de ficção ou didático.",
    "Dica8": "Tenho sumário ou índice.",
    "Dica9": "Pessoas gostam do cheiro das folhas novas.",
    "Dica10": "Sou lido da esquerda para a direita no Ocidente."
  },
  {
    "Categoria": "Coisa",
    "Resposta": "Telefone",
    "Dica1": "Sou objeto de comunicação.",
    "Dica2": "Facilitou a conexão à distância.",
    "Dica3": "Primeira versão surgiu no século XIX.",
    "Dica4": "Alexander Graham Bell é associado a mim.",
    "Dica5": "Antigamente precisava de cabos.",
    "Dica6": "Evoluí para versões sem fio.",
    "Dica7": "Quase todos carregam um no bolso.",
    "Dica8": "Antes de falar, ouvia-se um sinal de discagem.",
    "Dica9": "Tenho números e teclas.",
    "Dica10": "Minha função é realizar chamadas de voz."
  },
  {
    "Categoria": "Evento",
    "Resposta": "Copa do Mundo",
    "Dica1": "Evento de maior audiência do planeta.",
    "Dica2": "Ocorro a cada quatro anos.",
    "Dica3": "Reúno seleções de todos os continentes.",
    "Dica4": "Sou organizado pela FIFA.",
    "Dica5": "O país sede muda a cada edição.",
    "Dica6": "O vencedor recebe troféu de ouro.",
    "Dica7": "Brasil participou de todas as edições.",
    "Dica8": "Pelé e Maradona brilharam em mim.",
    "Dica9": "Pessoas colecionam álbuns de figurinhas.",
    "Dica10": "Principal torneio mundial de futebol."
  },
  {
    "Categoria": "Coisa",
    "Resposta": "Relógio",
    "Dica1": "Instrumento de medição.",
    "Dica2": "Inventado para organizar as atividades.",
    "Dica3": "Dependia do sol ou da areia.",
    "Dica4": "Posso ser analógico ou digital.",
    "Dica5": "Usado como acessório de moda.",
    "Dica6": "Tenho engrenagens ou circuitos.",
    "Dica7": "Posso emitir alarmes.",
    "Dica8": "Divido o dia em 24 partes.",
    "Dica9": "Tenho ponteiros.",
    "Dica10": "Objeto que serve para ver as horas."
  },
  {
    "Categoria": "Lugar",
    "Resposta": "Egito",
    "Dica1": "Localizado no Mediterrâneo.",
    "Dica2": "Uma das histórias mais antigas.",
    "Dica3": "Atravessado pelo Rio Nilo.",
    "Dica4": "Território coberto por deserto.",
    "Dica5": "Capital é o Cairo.",
    "Dica6": "Governantes eram divindades.",
    "Dica7": "Berço dos hieróglifos.",
    "Dica8": "Abrigo templos gigantescos.",
    "Dica9": "Destino de turistas pelas pirâmides.",
    "Dica10": "Abrigo a Grande Esfinge de Gizé."
  },
  {
    "Categoria": "Personagem",
    "Resposta": "Magic Kaito (Kaito Kid)",
    "Dica1": "Sou um personagem de mangá e anime criado por Gosho Aoyama.",
    "Dica2": "Minha primeira aparição ocorreu em 1987.",
    "Dica3": "Sou um mestre do disfarce e do ilusionismo.",
    "Dica4": "Assumi a identidade secreta que pertenceu ao meu pai.",
    "Dica5": "Frequentemente apareço como um rival brilhante na série Detective Conan.",
    "Dica6": "Utilizo dispositivos tecnológicos para realizar fugas impossíveis.",
    "Dica7": "Meu traje icônico é um terno branco com cartola e capa.",
    "Dica8": "Envio cartões de aviso antes de realizar meus roubos.",
    "Dica9": "Sou um ladrão de joias que busca a gema Pandora.",
    "Dica10": "Meu codinome internacional é Kaito Kid."
  },
  {
    "Categoria": "Personagem",
    "Resposta": "Misato Katsuragi",
    "Dica1": "Sou uma personagem central de uma aclamada série de ficção científica dos anos 90.",
    "Dica2": "Sou uma oficial de alto escalão em uma organização paramilitar.",
    "Dica3": "Atuo como guardiã e mentora dos jovens pilotos da trama.",
    "Dica4": "Tenho uma cicatriz no peito, única lembrança do Segundo Impacto.",
    "Dica5": "\"Sou uma estrategista brilhante em batalhas contra seres chamados \"\"Anjos\"\".\"",
    "Dica6": "Apesar da competência profissional, sou muito desorganizada em casa.",
    "Dica7": "Adoro beber cerveja e tenho um pinguim de estimação chamado Pen Pen.",
    "Dica8": "Minha patente é promovida de Capitã a Major durante a série.",
    "Dica9": "Trabalho para a organização secreta NERV.",
    "Dica10": "Sou a diretora de operações em Neon Genesis Evangelion."
  }
];